# TUTORIAL OF PYTORCH API 01 ==> STEP BY STEPS MANUALLY

## 1_Step by Steps Manually

In [242]:
import torch
import numpy as np
import random

In [243]:
x = torch.tensor([1,2,4,5], dtype=torch.float32)
y = torch.tensor([10,20,30,50], dtype=torch.float32)

print(x)
print(y)

tensor([1., 2., 4., 5.])
tensor([10., 20., 30., 50.])


In [244]:
w = torch.rand(1,dtype=torch.float32, requires_grad=True)
b = torch.rand(1,dtype=torch.float32, requires_grad=True)
print(w)
print(b)

tensor([0.2189], requires_grad=True)
tensor([0.1721], requires_grad=True)


In [245]:
def forward(x):
    return w*x + b
    

In [246]:
def loss(y, y_hat):
    return ((y_hat - y)**2).mean()

In [247]:
print("Prediction before of forward(5) " + str(forward(5)))
n_iters = 100
learning_rate = 0.01
for epoch in range(n_iters):
    #forward
    y_hat = forward(x)

    #cost value
    l = loss(y,y_hat)

    #gradients
    l.backward()

    #update parameters
    with torch.no_grad():
        w -= learning_rate*w.grad
        b -= learning_rate*b.grad

    w.grad.zero_()
    b.grad.zero_()
    if epoch % 10 == 0:
        print(f'epoch {epoch}, w= {w.item():.3f}, b={b.item():.3f},loss = {l.item():.8f}')
    
print("Prediction after of forward(5) " + str(forward(5)))


Prediction before of forward(5) tensor([1.2664], grad_fn=<AddBackward0>)
epoch 0, w= 2.258, b=0.706,loss = 920.38189697
epoch 10, w= 8.153, b=2.191,loss = 20.14499092
epoch 20, w= 8.522, b=2.213,loss = 16.90930939
epoch 30, w= 8.561, b=2.150,loss = 16.84736443
epoch 40, w= 8.579, b=2.084,loss = 16.80057907
epoch 50, w= 8.596, b=2.021,loss = 16.75749207
epoch 60, w= 8.612, b=1.960,loss = 16.71777725
epoch 70, w= 8.628, b=1.902,loss = 16.68116951
epoch 80, w= 8.643, b=1.846,loss = 16.64742661
epoch 90, w= 8.657, b=1.792,loss = 16.61632538
Prediction after of forward(5) tensor([45.0917], grad_fn=<AddBackward0>)


## 2_Pipeline

In [258]:
x = torch.tensor([1,2,4,5], dtype=torch.float32)
y = torch.tensor([10,20,30,50], dtype=torch.float32)

print(x)
print(y)

tensor([1., 2., 4., 5.])
tensor([10., 20., 30., 50.])


In [259]:
w = torch.rand(1,dtype=torch.float32, requires_grad=True)
b = torch.rand(1,dtype=torch.float32, requires_grad=True)

print(w)
print(b)

tensor([0.3816], requires_grad=True)
tensor([0.9219], requires_grad=True)


In [260]:
def forward(x):
    return w*x + b

In [261]:
print("Prediction befor of forward(5) " + str(forward(5)))
n_iters = 100
learning_rate = 0.01
loss = torch.nn.MSELoss()
optimizer = torch.optim.SGD([w], lr=learning_rate)
for epoch in range(n_iters):
    #forward
    y_hat = forward(x)

    #cost value
    l = loss(y, y_hat)

    #gradients
    l.backward()

    #update parameters
    optimizer.step()

    optimizer.zero_grad()
    if epoch % 10 == 0:
        print(f'epoch {epoch}, w= {w.item():.3f}, b= {b.item():.3f}, loss = {l.item():.8f}')
    
print("Prediction after of forward(5) " + str(forward(5)))

Prediction befor of forward(5) tensor([2.8299], grad_fn=<AddBackward0>)
epoch 0, w= 2.339, b= 0.922, loss = 848.79644775
epoch 10, w= 8.410, b= 0.922, loss = 20.75762367
epoch 20, w= 8.855, b= 0.922, loss = 16.31268883
epoch 30, w= 8.887, b= 0.922, loss = 16.28882790
epoch 40, w= 8.890, b= 0.922, loss = 16.28869820
epoch 50, w= 8.890, b= 0.922, loss = 16.28870010
epoch 60, w= 8.890, b= 0.922, loss = 16.28869438
epoch 70, w= 8.890, b= 0.922, loss = 16.28869438
epoch 80, w= 8.890, b= 0.922, loss = 16.28869438
epoch 90, w= 8.890, b= 0.922, loss = 16.28869438
Prediction after of forward(5) tensor([45.3716], grad_fn=<AddBackward0>)


## 3_Pipeline API

In [268]:
x = torch.tensor([[1],[2],[4],[5]], dtype=torch.float32)
y = torch.tensor([[10],[20],[30],[50]], dtype=torch.float32)

x_test = torch.tensor([5], dtype=torch.float32)
print(x)
print(y)


tensor([[1.],
        [2.],
        [4.],
        [5.]])
tensor([[10.],
        [20.],
        [30.],
        [50.]])


In [269]:
model = torch.nn.Linear(in_features=1,out_features=1)

In [270]:
print("Prediction before of model(x_test)= " + str(model(x_test).item()))
n_iters = 100
learning_rate = 0.01
loss = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(n_iters):
    #forward
    y_hat = model(x)

    #cost value
    l = loss(y, y_hat)

    #gradients
    l.backward()

    #update parameters
    optimizer.step()

    optimizer.zero_grad()
    if epoch % 10 == 0:
        [w,b] = model.parameters()
        print(f'epoch {epoch}, w= {w.item():.3f}, b= {b.item():.3f},loss = {l.item():.8f}')
    
print("Prediction after of model(x_test)= " + str(model(x_test).item()))

Prediction before of model(x_test)= -1.5939687490463257
epoch 0, w= 1.739, b= 1.105,loss = 1035.93347168
epoch 10, w= 8.003, b= 2.667,loss = 20.98074150
epoch 20, w= 8.397, b= 2.675,loss = 17.30628204
epoch 30, w= 8.443, b= 2.593,loss = 17.21194839
epoch 40, w= 8.466, b= 2.510,loss = 17.13663101
epoch 50, w= 8.487, b= 2.430,loss = 17.06724739
epoch 60, w= 8.508, b= 2.353,loss = 17.00328827
epoch 70, w= 8.528, b= 2.279,loss = 16.94433784
epoch 80, w= 8.546, b= 2.208,loss = 16.89001846
epoch 90, w= 8.565, b= 2.140,loss = 16.83991432
Prediction after of model(x_test)= 44.981834411621094


## 4_Advanced with Class Model

In [272]:
class LinearRegression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
    
    def forward(self,x):
        return self.linear(x)


In [274]:
model = LinearRegression(input_dim=1, output_dim=1)
print("Prediction before of model(x_test)= " + str(model(x_test).item()))
n_iters = 100
learning_rate = 0.01
loss = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(n_iters):
    #forward
    y_hat = model(x)

    #cost value
    l = loss(y, y_hat)

    #gradients
    l.backward()

    #update parameters
    optimizer.step()

    optimizer.zero_grad()
    if epoch % 10 == 0:
        [w,b] = model.parameters()
        print(f'epoch {epoch}, w= {w.item():.3f}, b= {b.item():.3f},loss = {l.item():.8f}')
    
print("Prediction after of model(x_test)= " + str(model(x_test).item()))


Prediction before of model(x_test)= -2.6253533363342285
epoch 0, w= 1.742, b= 0.365,loss = 1091.44384766
epoch 10, w= 8.168, b= 2.000,loss = 20.61393356
epoch 20, w= 8.566, b= 2.037,loss = 16.78608704
epoch 30, w= 8.605, b= 1.981,loss = 16.73181343
epoch 40, w= 8.622, b= 1.923,loss = 16.69406509
epoch 50, w= 8.637, b= 1.866,loss = 16.65931320
epoch 60, w= 8.652, b= 1.811,loss = 16.62728500
epoch 70, w= 8.666, b= 1.759,loss = 16.59775734
epoch 80, w= 8.679, b= 1.709,loss = 16.57054520
epoch 90, w= 8.692, b= 1.660,loss = 16.54546165
Prediction after of model(x_test)= 45.133296966552734
