In [12]:
import tensorflow as tf
import numpy as np
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# 1. ARRAY VS TENSOR VS PYTORCH #

## 1.1 ARRAY FROM PYTHON LIST ##

In [13]:
py_list = [1,2,3,4,5,6,7,8,9,10]
print("This is a list of python: ",py_list)
print("Type: ",type(py_list))

This is a list of python:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Type:  <class 'list'>


### 1.1.1 NUMPY ###

In [40]:
np_array = np.array([1,2,3,4,5])
print("This is an array of numpy: ", np_array)
print("Type :", type(np_array))
print("Dimension :", np_array.ndim)
print("Shape :", np_array.shape)
print("Dtype :", np_array.dtype)
print("Reshape: \n",np_array.reshape(-1,1))

This is an array of numpy:  [1 2 3 4 5]
Type : <class 'numpy.ndarray'>
Dimension : 1
Shape : (5,)
Dtype : int64
Reshape: 
 [[1]
 [2]
 [3]
 [4]
 [5]]


### 1.1.2 TENSORFLOW ###

#### Constant vs Variable ########

#### Constant() ####

In [48]:
# Constant fixed --> cannot change for training to update parameters
tf_tensor1 = tf.constant([1,2,3,4,5])
print("This is a tensor of constant tensorflow: ", tf_tensor1)
print("Type :", type(tf_tensor1))
print("Dimension :",tf_tensor1.ndim)
print("Shape :", tf_tensor1.shape)
print("Dtype :", tf_tensor1.dtype)
print("Reshape : \n",tf.reshape(tf_tensor1,(-1,1)))

This is a tensor of constant tensorflow:  tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Type : <class 'tensorflow.python.framework.ops.EagerTensor'>
Dimension : 1
Shape : (5,)
Dtype : <dtype: 'int32'>
Reshape : 
 tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1), dtype=int32)


#### Variable() ####

In [50]:
# Variable change for training to update parameters
tf_tensor2 = tf.Variable([1,2,3,4,5])
print("This is a tensor of Variable tensorflow: ", tf_tensor2)
print("Type :", type(tf_tensor2))
print("Dimension :",tf_tensor2.numpy().ndim)
print("Shape :", tf_tensor2.shape)
print("Dtype :", tf_tensor2.dtype)
print("Reshape : \n",tf.reshape(tf_tensor2,(-1,1)))

This is a tensor of Variable tensorflow:  <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>
Type : <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
Dimension : 1
Shape : (5,)
Dtype : <dtype: 'int32'>
Reshape : 
 tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]], shape=(5, 1), dtype=int32)


## 1.2 Zeros, Ones, Linspace ##

### 1.2.1 Numpy ###

#### zeros() ####

In [54]:
np_zeros = np.zeros(shape=(3,3))
print("Zeros function of numpy: \n",np_zeros)

Zeros function of numpy: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### ones() ####

In [55]:
np_ones = np.ones(shape=(3,3))
print("ones function of numpy: \n",np_ones)

ones function of numpy: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### linspace() ####

In [61]:
np_linspace = np.linspace(0,10,5)
print("linspace function of numpy: \n",np_linspace)

linspace function of numpy: 
 [ 0.   2.5  5.   7.5 10. ]


### 1.2.2 Tensorflow ###

#### zeros() ####

In [63]:
tf_ones = tf.zeros(shape=(3,3))
print("zeros function of tensorflow: \n",tf_ones)

zeros function of tensorflow: 
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


#### ones() ####

In [64]:
tf_ones = tf.ones(shape=(3,3))
print("ones function of tensorflow: \n",tf_ones)

ones function of tensorflow: 
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


#### linspace() ####

In [65]:
tf_linspace = tf.linspace(0,10,5)
print("linspace function of tensorflow: \n",tf_linspace)

linspace function of tensorflow: 
 tf.Tensor([ 0.   2.5  5.   7.5 10. ], shape=(5,), dtype=float64)


## 1.3 Arrange(Numpy) vs Range(Tensorflow), Full(Numpy) vs Fill(Tensorflow) ##

### 1.3.1 Numpy ###

#### arrange() ####

In [66]:
np_arrange = np.arange(0,10,1)
print("arrange function of numpy: ", np_arrange)

arrange function of numpy:  [0 1 2 3 4 5 6 7 8 9]


#### full() ####

In [74]:
np_full = np.full((3,3), 3)
print("full function of numpy: \n", np_full)

full function of numpy: 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


### 1.3.2 Tensorflow ###

#### range() ####

In [75]:
tf_range = tf.range(0,10,1)
print("range function of tensorflow: ", tf_range)

range function of tensorflow:  tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


#### fill() ####

In [77]:
tf_fill = tf.fill((3,3), 3)
print("fill function of tensorflow: \n", tf_fill)

fill function of tensorflow: 
 tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)


## 1.4 Random ##

### 1.4.1 Numpy ###

In [89]:
np.random.seed(1)
np_random1 = np.random.random((3,3))
print("random function of numpy have shape: \n", np_random1)

np_random2 = np.random.rand(3,3)
print("random function of numpy without shape: \n", np_random2)

np_random3 = np.random.randint(0,10,(3,3))
print("random function of numpy with int value: \n", np_random3)

np_random4 = np.random.normal(0, 1, (3,3))
print("random function of numpy with normal distribution: \n", np_random4)


random function of numpy have shape: 
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
random function of numpy without shape: 
 [[0.53881673 0.41919451 0.6852195 ]
 [0.20445225 0.87811744 0.02738759]
 [0.67046751 0.4173048  0.55868983]]
random function of numpy with int value: 
 [[7 0 6]
 [9 9 7]
 [6 9 1]]
random function of numpy with normal distribution: 
 [[ 0.17532267  0.19443089 -0.53524902]
 [ 0.77735121  0.17133845 -0.44285144]
 [ 1.70490377  0.92434585 -1.30486124]]


### 1.4.2 Tensorflow ###

In [116]:
tf.random.set_seed(1)
tf_random1 = tf.random.uniform((3,3))
print("random function of tensorflow: \n", tf_random1)

tf_random2 = tf.random.uniform((3,3), minval=0, maxval=1)
print("random function of tensorflow: \n", tf_random2)

tf_random3 = tf.random.uniform((3,3), minval=0, maxval=10, dtype=tf.int32)
print("random function of tensorflow with int value: \n", tf_random3)

tf_random4 = tf.random.normal((3,3), mean=0, stddev=1)
print("random function of tensorflow with normal distribution: \n", tf_random4)

random function of tensorflow: 
 tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]], shape=(3, 3), dtype=float32)
random function of tensorflow: 
 tf.Tensor(
[[0.51010704 0.44353175 0.4085331 ]
 [0.9924923  0.68866396 0.34584963]
 [0.436067   0.601061   0.45662427]], shape=(3, 3), dtype=float32)
random function of tensorflow with int value: 
 tf.Tensor(
[[5 8 6]
 [6 4 9]
 [4 4 3]], shape=(3, 3), dtype=int32)
random function of tensorflow with normal distribution: 
 tf.Tensor(
[[ 1.6940169   0.1196931  -1.15846   ]
 [ 0.17260402 -0.7144965   0.68960047]
 [-1.090816   -1.1865102  -1.302188  ]], shape=(3, 3), dtype=float32)


## 1.5 Slicing, Indexing, Concatenating ##

### 1.5.1 Numpy ###

#### Slicing ####

In [117]:
np_array = np.random.randint(1,10, (3,3))
print(np_array)
print("Get first-2rows: \n",np_array[:2, :])
print("Get first-2cols: \n",np_array[:, :2])

[[1 4 5]
 [8 6 4]
 [9 9 1]]
Get first-2rows: 
 [[1 4 5]
 [8 6 4]]
Get first-2cols: 
 [[1 4]
 [8 6]
 [9 9]]


#### Indexing ####

In [118]:
np_array = np.random.randint(1,10, (3,3))
print(np_array)
print("Get index of [1][1]: ", np_array[1,1])

[[7 8 6]
 [5 6 3]
 [6 7 7]]
Get index of [1][1]:  6


#### Concatenating

In [119]:
np_array1 = np.random.randint(1,10, (2,2))
np_array2 = np.random.randint(1,10, (2,2))
print(np_array1)
print(np_array2)
print("Concatenate 2 arrays follow vertical axis: \n", np.concatenate([np_array1, np_array2], axis=0))
print("Concatenate 2 arrays follow horizontial axis: \n", np.concatenate([np_array1, np_array2], axis=1))

[[9 8]
 [8 8]]
[[3 7]
 [1 6]]
Concatenate 2 arrays follow vertical axis: 
 [[9 8]
 [8 8]
 [3 7]
 [1 6]]
Concatenate 2 arrays follow horizontial axis: 
 [[9 8 3 7]
 [8 8 1 6]]


### 1.5.2 Tensorflow ###

#### Slicing

In [120]:
tf_tensor = tf.random.uniform((3,3),  minval= 0, maxval =10, dtype=tf.int32)
print(tf_tensor)
print("Get first-2rows: \n",tf_tensor[:2, :])
print("Get first-2cols: \n",tf_tensor[:, :2])

tf.Tensor(
[[4 4 9]
 [2 1 0]
 [7 8 3]], shape=(3, 3), dtype=int32)
Get first-2rows: 
 tf.Tensor(
[[4 4 9]
 [2 1 0]], shape=(2, 3), dtype=int32)
Get first-2cols: 
 tf.Tensor(
[[4 4]
 [2 1]
 [7 8]], shape=(3, 2), dtype=int32)


#### Indexing

In [121]:
tf_tensor = tf.random.uniform((3,3), minval=0, maxval=10, dtype=tf.int32)
print(tf_tensor)
print("Get index of [1][1]: ", tf_tensor[1,1])

tf.Tensor(
[[5 0 5]
 [5 2 8]
 [3 9 3]], shape=(3, 3), dtype=int32)
Get index of [1][1]:  tf.Tensor(2, shape=(), dtype=int32)


#### Concatenating

In [123]:
tf_tensor1 = tf.random.uniform((2,2), minval=1, maxval=10, dtype=tf.int32)
tf_tensor2 = tf.random.uniform((2,2), minval=1, maxval=10, dtype=tf.int32)
print(tf_tensor1)
print(tf_tensor2)
print("Concatenate 2 tensors follow vertical axis: \n", tf.concat([tf_tensor1, tf_tensor2], axis=0))
print("Concatenate 2 tensors follow horizontial axis: \n", tf.concat([tf_tensor1, tf_tensor2], axis=1))

tf.Tensor(
[[6 3]
 [5 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 1]
 [2 6]], shape=(2, 2), dtype=int32)
Concatenate 2 tensors follow vertical axis: 
 tf.Tensor(
[[6 3]
 [5 8]
 [2 1]
 [2 6]], shape=(4, 2), dtype=int32)
Concatenate 2 tensors follow horizontial axis: 
 tf.Tensor(
[[6 3 2 1]
 [5 8 2 6]], shape=(2, 4), dtype=int32)


## 1.6  Calculation ##

### 1.6.1 Numpy ###

In [131]:
np_array1 = np.random.randint(1,10, (2,2))
np_array2 = np.random.randint(1,10, (2,2))
print("Original array1: \n",np_array1)
print("Original array2: \n",np_array2)

print("Add 2 arrays: \n", np.add(np_array1, np_array2))
print("Sub 2 arrays: \n",np.subtract(np_array1, np_array2))
print("Mul 2 arrays: \n", np.multiply(np_array1, np_array2))
print("Div 2 arrays: \n", np.divide(np_array1, np_array2))

Original array1: 
 [[3 9]
 [6 1]]
Original array2: 
 [[6 9]
 [7 7]]
Add 2 arrays: 
 [[ 9 18]
 [13  8]]
Sub 2 arrays: 
 [[-3  0]
 [-1 -6]]
Multiply 2 arrays: 
 [[18 81]
 [42  7]]
Divide 2 arrays: 
 [[0.5        1.        ]
 [0.85714286 0.14285714]]


### 1.6.2 Tensorflow ###

In [134]:
tf_tensor1 = tf.random.uniform((2,2), minval=1, maxval=10, dtype=tf.int32)
tf_tensor2 = tf.random.uniform((2,2), minval=1, maxval=10, dtype=tf.int32)
print("Original tensor1: \n",tf_tensor1)
print("Original tensor2: \n",tf_tensor2)

print("Add 2 tensors: \n",tf.add(tf_tensor1, tf_tensor2))
print("Sub 2 tensors: \n",tf.subtract(tf_tensor1, tf_tensor2))
print("Mul 2 tensors: \n",tf.multiply(tf_tensor1, tf_tensor2))
print("Div 2 tensors: \n",tf.divide(tf_tensor1, tf_tensor2))



Original tensor1: 
 tf.Tensor(
[[8 2]
 [2 5]], shape=(2, 2), dtype=int32)
Original tensor2: 
 tf.Tensor(
[[2 2]
 [2 7]], shape=(2, 2), dtype=int32)
Add 2 tensors: 
 tf.Tensor(
[[10  4]
 [ 4 12]], shape=(2, 2), dtype=int32)
Sub 2 tensors: 
 tf.Tensor(
[[ 6  0]
 [ 0 -2]], shape=(2, 2), dtype=int32)
Mul 2 tensors: 
 tf.Tensor(
[[16  4]
 [ 4 35]], shape=(2, 2), dtype=int32)
Div 2 tensors: 
 tf.Tensor(
[[4.         1.        ]
 [1.         0.71428571]], shape=(2, 2), dtype=float64)


# 1.7 Dot Product

### 1.7.1 Numpy

In [144]:
np_array1 = np.arange(1,5)
np_array2 = np.arange(5,9)
print("Original array1: \n",np_array1)
print("Original array2: \n",np_array2)
print("Dot product in numpy: \n",np.dot(np_array1, np_array2))

Original array1: 
 [1 2 3 4]
Original array2: 
 [5 6 7 8]
Dot product in numpy: 
 70


### 1.7.2 Tensorflow

In [149]:
tf_tensor1 = tf.range(1,5)
tf_tensor2 = tf.range(5,9)
print("Original array1: \n",tf_tensor1)
print("Original array2: \n",tf_tensor2)
print("Dot product in numpy: \n",tf.tensordot(tf_tensor1, tf_tensor2, axes=1))

Original array1: 
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Original array2: 
 tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
Dot product in numpy: 
 tf.Tensor(70, shape=(), dtype=int32)
